### ISSUE TITLE
IMAP邮箱的邮件详情的附件下载区域布局问题

### ISSUE THREAD

**Issue by cowmax** [ECCloud/iOSClient#15]
1. 附件的Size 与附件名称混淆在一起
2. 附件的“下载”按钮样式怪异
3. 附件名称只有一行，显然信息不足够

**Comment by ThinkingWong** [comment]
刘工，您好，该问题已修复。

**Comment by cowmax** [comment]
请参照其他邮件客户端样式进行修改
（1）修改：一个和多个附件时的部局
（2）修改：附件文档图标（参照Win8）
（3）修改：附件未下载、已下载状态图标
