### ISSUE TITLE
IMAP邮箱下载邮件列表后不显示邮件摘要

### ISSUE THREAD

**Issue by cowmax** [ECCloud/iOSClient#20]

**Comment by ThinkingWong** [comment]
刘工，您好，现在摘要不是截取正文显示的，因为正文是html，格式是未知的，故摘要也是从服务器获取的，不能截取正文作为摘要，如果未获取到，则显示空白。

**Comment by cowmax** [comment]
目前看到的情况是：由于邮件列表没有及时刷新，导致摘要获取回来之后，邮件项未显示摘要内容。
