### ISSUE TITLE
企业彩云-iPhone客户端通讯录初始化时遇到问题

### ISSUE THREAD

**Issue by cowmax** [ECCloud/iOSClient#7]
在iPad Air 上安装iPhone版本客户端（公众版），通讯录数据初始化完毕之后，切换到通讯录时，“卡死”在附件所示界面。请跟进。

**Comment by cowmax** [comment]
同样的问题再次发生（在iPad mini） 上。

**Comment by ThinkingWong** [comment]
刘工，您好，该问题在上线版本中已修复。谢谢！
